image: maven:3.6.1-jdk-8

variables:

# application properties - These are application level properties.
    GITLAB_REPO: gitlab.com/swaminathan_apisero/world-timezone-app.git
    LOCAL_REPO: C:/opt/maven/v361repo

    
#runtime properties
    #Runtime properties can be defined here.

#anypoint environment properties
    # DEV ENVIRONMENT
    ANYPOINT_ENVIRONMENT_DEV: Sandbox
    # UAT ENVIRONMENT
    ANYPOINT_ENVIRONMENT_UAT: Sandbox
    # PROD ENVIRONMENT
    ANYPOINT_ENVIRONMENT_PROD: Sandbox
    
    APPLICATION_NAME_DEV: mule4-deploy-demo
    APPLICATION_NAME_UAT: mule4-deploy-demo
    ARTIFACT_NAME: mule4-deploy-demo-1.0.0-SNAPSHOT-mule-application.jar

    

stages: 
    - .pre
    # - tags
    - build_dev
    - deploy_dev
    #- build_uat
    #- deploy_uat
    # - build_prod
    # - deploy_prod
    - .post
    
# tags:
    # stage: tags
    # script:
        # - git remote set-url origin https://$GITLAB_USERNAME:$GITLAB_PASSWORD@$GITLAB_REPO
        # - git config user.name "swaminathan_apisero"
        # - git config user.email "swaminathan.star@gmail.com"
        # - git tag -a $version -m "UAT released in this tag."
        # - git push --tags
    # only:
        # refs:
            # - uat && $version
    
build_dev:
    # tags:
       # - ci
     stage: build_dev
     script: 
         - mvn clean package -DskipTests
     allow_failure: false
     artifacts:
         paths:
           - target/
         when: always
         expire_in: 1 hour
     only:
         refs:
             - develop
    
        
deploy_dev:
    #tags:
       #- ci
    stage: deploy_dev
    script:
        - "mvn deploy -DmuleDeploy -Dmule.artifact=target/$ARTIFACT_NAME -Danypoint.uri=$ANYPOINT_URI -Danypoint.username=$ANYPOINT_USERNAME -Danypoint.password=$ANYPOINT_PASSWORD -DbusinessGroup=$BUSINESS_GROUP -Denvironment=$ANYPOINT_ENVIRONMENT_DEV -Dworkers=$WORKERS -DworkerType=$WORKER_TYPE -DapplicationName=$APPLICATION_NAME_DEV -Danypoint.platform.client_id=$ANYPOINT_CLIENT_ID_DEV -Danypoint.platform.client_secret=$ANYPOINT_CLIENT_SECRET_DEV -DskipTests -X"
    when: on_success
    only:
        refs:
            - develop

# build_uat: 
    # stage: build_uat
 
    # script: 
        # - mvn clean package -DskipTests
    # allow_failure: false
    # when: on_success
    # artifacts:
        # paths:
          # - target/
        # when: always
        # expire_in: 1 hour
    # only:
        # refs:
            # - uat 
